### ISSUE TITLE
DbMerge (with ExpandoObject) and ChageDate/ChangeAction Properties

### ISSUE THREAD

**Issue by frefardt** [etlbox/etlbox#87] opened 2021-01-29 16:22 UTC
Hi there

I have a DataFlow that reads data from a source and merges it into a database table. I therefore want to log what exactly happens per row and use the default properties ChangeDate and ChangeAction. That works as described and expected.

But. The log is not very helpful. I don't know exactly what row has been updated/inserted or deleted. It would be great to have 2 additional properties available. 1. The tableName of the merge destination and 2.  a concationation/List of the IdColumn properties (identity). 

With that information it is possible to trace (join) back to the merged row and see exactly what happend during the merge operation.

Would this be possible to implement on your side? 

Regards
Florian

**Comment by andreaslennartz** [comment] 2021-01-29 20:48
Hi @frefardt ,

thanks for reporting this.
I am not quite sure if I understand what you actually need to have improved.
With "log", are you referring to the log output (product if you add a nlog.config with a target to your project) or the delta data that you consume from the DbMerge?
Please note that (starting with version 2.3.0) the delta list which was a property on the DbMerge is removed - you will only get the delta rows when you connect the DbMerge to a destination, e.g. like this:

```
            var source = new MemorySource<MyMergeRow>();            
            var dest = new DbMerge<MyMergeRow>(connection, "DBMergeDeltaDestination");
            var delta = new MemoryDestination<MyMergeRow>();
            source.LinkTo(dest).LinkTo(delta);
            source.Execute();
```

The delta destination will then contain all rows and their corresponding ChangeDate/ChangeAction (Insert/Update/Delete/Exists).
The table name of the merge destination can be read from `dest.DestinationTableDefininition.Name`  after you have started the flow. 
The `dest.MergeProperties.IdColumns` will contain the IdColumns (currently) only if you add them here in the code. If you set the attributes on the object directly, this property won't reflect this information. I am planning to change this in one of the future versions. 
Is this what you had in mind? Or could you describe a little more what kind of properties you are missing?

**Comment by frefardt** [comment] 2021-01-30 08:50
Hi @andreaslennartz 

Thanks for your help with this! I'm using the most current version of ETLBox; 2.3.0. In fact I was doing a similar example like you are mentioning above. And I now found the issue why I could not get the desired property fields in my table. The reason why is that I used the DbMerge connector instead of DbDestination to persist the results on the 'delta' table.

Now I discovered something else: The first time when I execute my workflow and the 'delta' table is empty everything works fine and the data gets inserted. The second time when I execute the same workflow, even without modifications on the source table, the workflow runs into this error:

```
System.AggregateException: One or more errors occurred. (Failed to convert parameter value from a String to a Int16.)
 ---> System.FormatException: Failed to convert parameter value from a String to a Int16.
 ---> System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.String.System.IConvertible.ToInt16(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Microsoft.Data.SqlClient.SqlParameter.CoerceValue(Object value, MetaType destinationType, Boolean& coercedToDataFeed, Boolean& typeChanged, Boolean allowStreaming)
   --- End of inner exception stack trace ---
   at ETLBox.DataFlow.DataFlowComponent.CleanUpComponent(Task t)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at ETLBox.DataFlow.Network.Execute(DataFlowComponent[] nodes)
```

My 'delta' table looks like this:

```
CREATE TABLE [dbo].[mergeTable](
	[ID] [int] NULL,
	[Col1] [nvarchar](100) NULL,
	[Col2] [smallint] NULL,
	[ChangeDate] [datetime] NULL,
	[ChangeAction] [nvarchar](1000) NULL
) ON [PRIMARY]
```

And my 'dest' table like this (source is similar to this):

```
CREATE TABLE [dbo].[destTable](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Col1] [nvarchar](100) NULL,
	[Col2] [smallint] NULL
) ON [PRIMARY]
```

I only tested this on SqlServer 2019 but will try on Postgress as well today to see if the error replicates.

Can you have a look at this? I have no clue why this happens.

Regards
Florian

**Comment by andreaslennartz** [comment] 2021-01-30 09:51
Hi @frefardt ,

so the first part of your request has basically been resolved?
Sure, I will look into this bug. Could you provide me some source/example code how the actual data flow looks like? I assume you are using strong typed objects (Pocos), so I also would be interested how your Pocos are defined?
This would help me to reproduce this bug in my test environment.

**Comment by frefardt** [comment] 2021-01-30 11:18
Hi @andreaslennartz 

Exactly, the first part has been resolved.

Regarding the code. I use ExpandoObject and not Pocos. Therefore it is basicly the same like you wrote above, with the exeption that I read and write to SqlServer.

But here is the snipet where I link it all together and execute it.
```
           var source = sourceConnector.LinkTo(destinationConnector);

            if (component.DestinationConnector.DbConnector.DbMerge != null)
            {
             var delta = (DbDestination)await findDbDestinationConnectorByType( // do some stuff to resolve the DbDestination connector)
                
                source.LinkTo(delta);
            }

            Network.Execute((DataFlowComponent)sourceConnector);
```

Regards Florian

**Comment by frefardt** [comment] 2021-01-31 17:05
Hi @andreaslennartz 

There was a bug in my code. I didn't realize that DbMerge is a 'special breed' in that sense that it implements IDataFlowDestination and **IDataFlowSource**. And I just treated it as a destination.

That now makes sense to me, because the result of the merge is treated as a destination and if you forward it to a 'delta' destination it has to be treated as a source.

I had to change one of my interfaces and now it works fine. You can close this issue.

Regards Florian

**Comment by andreaslennartz** [comment] 2021-01-31 20:27
Hi Florian,

thanks for the update. 
Yes, the DbMerge is a little bit different than other connectors. If it is the placed at the end of your flow, it will behave like a destination. But if you link it to other components, then it will also work like a source (or it will actually behave like a transformation) - input data is then written into the target table of the DbMerge, but it will also send the delta information into the flow for further processing. 
I will close the issue. Let me know if you encounter any other issues.

**Closed by andreaslennartz** 2021-01-31 20:27 UTC
Labels: enhancement
